[package]
name = "agt-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.agt-core]
path = "../crates/agt-core"

[[bin]]
name = "manifest_decode"
path = "fuzz_targets/manifest_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "contained_join"
path = "fuzz_targets/contained_join.rs"
test = false
doc = false
bench = false

[[bin]]
name = "tag_timestamp"
path = "fuzz_targets/tag_timestamp.rs"
test = false
doc = false
bench = false
